export const assetConstants = {
    COINS: {
        FETCH_ASSET_REQUEST: 'COINS::FETCH_ASSET_REQUEST',
        FETCH_ASSET_SUCCESS: 'COINS::FETCH_ASSET_SUCCESS',
        FETCH_ASSET_FAILURE: 'COINS::FETCH_ASSET_FAILURE',
        
        POST_ASSET_REQUEST: 'COINS::POST_ASSET_REQUEST',
        POST_ASSET_SUCCESS: 'COINS::POST_ASSET_SUCCESS',
        POST_ASSET_FAILURE: 'COINS::POST_ASSET_FAILURE',
    },
    LISTINGS: {
        FETCH_ASSET_REQUEST: 'LISTINGS::FETCH_ASSET_REQUEST',
        FETCH_ASSET_SUCCESS: 'LISTINGS::FETCH_ASSET_SUCCESS',
        FETCH_ASSET_FAILURE: 'LISTINGS::FETCH_ASSET_FAILURE',

        POST_ASSET_REQUEST: 'LISTINGS::POST_ASSET_REQUEST',
        POST_ASSET_SUCCESS: 'LISTINGS::POST_ASSET_SUCCESS',
        POST_ASSET_FAILURE: 'LISTINGS::POST_ASSET_FAILURE',
    },
    BIDS: {
        FETCH_ASSET_REQUEST: 'BIDS::FETCH_ASSET_REQUEST',
        FETCH_ASSET_SUCCESS: 'BIDS::FETCH_ASSET_SUCCESS',
        FETCH_ASSET_FAILURE: 'BIDS::FETCH_ASSET_FAILURE',

        POST_ASSET_REQUEST: 'BIDS::POST_ASSET_REQUEST',
        POST_ASSET_SUCCESS: 'BIDS::POST_ASSET_SUCCESS',
        POST_ASSET_FAILURE: 'BIDS::POST_ASSET_FAILURE',
    },
}
