export const assetConstants = {
    COINS: {
        FETCH_ASSET_REQUEST: 'COINS::FETCH_ASSET_REQUEST',
        FETCH_ASSET_SUCCESS: 'COINS::FETCH_ASSET_SUCCESS',
        FETCH_ASSET_FAILURE: 'COINS::FETCH_ASSET_FAILURE',
    },
    LISTINGS: {
        FETCH_ASSET_REQUEST: 'LISTINGS::FETCH_ASSET_REQUEST',
        FETCH_ASSET_SUCCESS: 'LISTINGS::FETCH_ASSET_SUCCESS',
        FETCH_ASSET_FAILURE: 'LISTINGS::FETCH_ASSET_FAILURE',
    }
}
