export const sessionConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',

    REFETCH_USER_REQUEST: 'REFETCH_USER_REQUEST',
    REFETCH_USER_SUCCESS: 'REFETCH_USER_SUCCESS',
    REFETCH_USER_FAILURE: 'REFETCH_USER_FAILURE',
};
